/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvfiltersystem;

import FileReaderSupport.TextFileReader;
import FileReaderSupport.WordFileReader;
import Support.Degrees;
import Support.ResumeListSupport;
import Support.ResumesFilter;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import model.EducationListModel;
import org.apache.commons.io.FilenameUtils;


/**
 *
 * @author Sarosh Madara
 */
public class MainScreen extends javax.swing.JFrame {
    
    /**
     * Creates new form MainScreen
     */
    String[] associate = null;
    String[] bachelor = null;
    String[] master = null;
    String[] doctoral = null;
    
    public MainScreen() {
        
        associate       = Degrees.getAssociationPrograms();
        bachelor        = Degrees.getBachelorPrograms();
        master          = Degrees.getMasterPrograms();
        doctoral        = Degrees.getDoctoralPrograms();
        
        initComponents();
        
        
        
        
        
        addJobPanel.setVisible(false);
        addJobEducationPanel.setVisible(false);
        
    }
    
    File[] myResumes;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser = new javax.swing.JFileChooser();
        resumesViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        resumesViewListPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resumeJListMainScreen = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addJobPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jobTitleTextField = new javax.swing.JTextField();
        jobExperienceTextField = new javax.swing.JTextField();
        jobPositionsTextField = new javax.swing.JTextField();
        jobSalaryTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jobPublishDateTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jobFinalApplyDateTextField = new javax.swing.JTextField();
        jobNightJCheckBox = new javax.swing.JCheckBox();
        jobDayJCheckBox = new javax.swing.JCheckBox();
        postJobjButton = new javax.swing.JButton();
        jobListPanel = new javax.swing.JPanel();
        addJobEducationPanel = new javax.swing.JPanel();
        associateDegreejComboBox = new JComboBox(associate);
        jLabel15 = new javax.swing.JLabel();
        bachelorDegreejComboBox = new JComboBox(bachelor);
        jLabel13 = new javax.swing.JLabel();
        masterDegreejComboBox = new JComboBox(master);
        jLabel16 = new javax.swing.JLabel();
        doctoralDegreejComboBox = new JComboBox(doctoral);
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        associateDegreejList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        bachelorDegreejList = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        masterDegreejList = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        doctoralDegreejList = new javax.swing.JList();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        generateJobMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        filechooser.setFileFilter(new ResumesFilter());
        filechooser.setMultiSelectionEnabled(true);
        filechooser.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(Support.ScreenAdjustment.getScreenSize()
        );
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resumesViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea.setBackground(new java.awt.Color(255, 255, 204));
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        resumesViewPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 610));

        resumesViewListPanel.setBackground(new java.awt.Color(255, 255, 204));
        resumesViewListPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resumeJListMainScreen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resumeJListMainScreenValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(resumeJListMainScreen);

        resumesViewListPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cvfiltersystem/images.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cvfiltersystem/minus.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 264, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        resumesViewListPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 310, 20));

        resumesViewPanel.add(resumesViewListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 310, -1));

        getContentPane().add(resumesViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -5, 890, 690));

        jLabel3.setText("Title");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Job Details");

        jLabel6.setText("Experience");

        jLabel7.setText("Positions");

        jLabel8.setText("Shifts");

        jLabel9.setText("Salary");

        jobSalaryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobSalaryTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Publish Date");

        jobPublishDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobPublishDateTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Final Date");

        jobFinalApplyDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobFinalApplyDateTextFieldActionPerformed(evt);
            }
        });

        jobNightJCheckBox.setText("Night");

        jobDayJCheckBox.setText("Day");

        postJobjButton.setText("Next");
        postJobjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postJobjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addJobPanelLayout = new javax.swing.GroupLayout(addJobPanel);
        addJobPanel.setLayout(addJobPanelLayout);
        addJobPanelLayout.setHorizontalGroup(
            addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJobPanelLayout.createSequentialGroup()
                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJobPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4)
                        .addGap(177, 177, 177)
                        .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addJobPanelLayout.createSequentialGroup()
                                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(69, 69, 69)
                                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addJobPanelLayout.createSequentialGroup()
                                        .addComponent(jobDayJCheckBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(jobNightJCheckBox))
                                    .addComponent(jobPositionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jobExperienceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jobTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jobSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jobPublishDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addJobPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(79, 79, 79)
                                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(postJobjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jobFinalApplyDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(addJobPanelLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel5)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        addJobPanelLayout.setVerticalGroup(
            addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJobPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5)
                .addGap(68, 68, 68)
                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jobTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobExperienceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jobPositionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jobNightJCheckBox)
                    .addComponent(jobDayJCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jobSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJobPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))
                    .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jobPublishDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addJobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jobFinalApplyDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(postJobjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        getContentPane().add(addJobPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -3, 890, 690));

        javax.swing.GroupLayout jobListPanelLayout = new javax.swing.GroupLayout(jobListPanel);
        jobListPanel.setLayout(jobListPanelLayout);
        jobListPanelLayout.setHorizontalGroup(
            jobListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jobListPanelLayout.setVerticalGroup(
            jobListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(jobListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 710));

        associateDegreejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associateDegreejComboBoxActionPerformed(evt);
            }
        });

        jLabel15.setText("Master Degree");

        bachelorDegreejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bachelorDegreejComboBoxActionPerformed(evt);
            }
        });

        jLabel13.setText("Associate Degree");

        jLabel16.setText("Doctoral Degree");

        jLabel14.setText("Bachelor Degree");

        associateDegreejList.setModel(EducationListModel.getInstance());
        jScrollPane3.setViewportView(associateDegreejList);

        bachelorDegreejList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(bachelorDegreejList);

        masterDegreejList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(masterDegreejList);

        doctoralDegreejList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(doctoralDegreejList);

        javax.swing.GroupLayout addJobEducationPanelLayout = new javax.swing.GroupLayout(addJobEducationPanel);
        addJobEducationPanel.setLayout(addJobEducationPanelLayout);
        addJobEducationPanelLayout.setHorizontalGroup(
            addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJobEducationPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJobEducationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(associateDegreejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addJobEducationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bachelorDegreejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addJobEducationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(masterDegreejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addJobEducationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctoralDegreejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        addJobEducationPanelLayout.setVerticalGroup(
            addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJobEducationPanelLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(associateDegreejComboBox)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bachelorDegreejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addJobEducationPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addJobEducationPanelLayout.createSequentialGroup()
                        .addGroup(addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(masterDegreejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(addJobEducationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctoralDegreejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(366, 366, 366))
        );

        getContentPane().add(addJobEducationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -4, 890, 710));

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Jobs");

        generateJobMenuItem.setMnemonic('c');
        generateJobMenuItem.setText("Generate Job");
        generateJobMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateJobMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(generateJobMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        setSize(new java.awt.Dimension(903, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

   
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
       openDialogForFiles();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void readFile(File file){
        
        switch(FilenameUtils.getExtension(file.getAbsolutePath())){
            case "txt":
                TextFileReader fileReader = new TextFileReader();
                fileReader.readTextFile(textArea, file);
                System.out.println("txt file found");
                break;
            case "doc":
                WordFileReader wordFileReader = new WordFileReader();
                wordFileReader.readWordFile(file,textArea);
                System.out.println("doc file found");
                break;
            case "docx":
                WordFileReader wordFileReaderDocx = new WordFileReader();
                wordFileReaderDocx.readDocxWordFile(file,textArea);
                System.out.println("docx file found");
                break;
            default:
                System.out.println("unknown file found");
                break;
        }
    }
    
    private void openDialogForFiles(){
        int returnValue = filechooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            if(filechooser.getSelectedFiles().length == 1){
                File file = filechooser.getSelectedFile();

                resumeJListMainScreen.setModel(ResumeListSupport.getModel(file));

                readFile(file);
            }else if(filechooser.getSelectedFiles().length > 1){
                myResumes = filechooser.getSelectedFiles();

                resumeJListMainScreen.setModel(ResumeListSupport.getModel(myResumes)); 
            }

        } else {
            System.out.println("File access cancelled by user.");
        }
    }
    
    private void resumeJListMainScreenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resumeJListMainScreenValueChanged
        File file = myResumes[resumeJListMainScreen.getSelectedIndex()];
        readFile(file);
    }//GEN-LAST:event_resumeJListMainScreenValueChanged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        openDialogForFiles();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void generateJobMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateJobMenuItemActionPerformed
        resumesViewPanel.setVisible(false);
        addJobPanel.setVisible(true);
    }//GEN-LAST:event_generateJobMenuItemActionPerformed

    private void jobSalaryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobSalaryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobSalaryTextFieldActionPerformed

    private void jobPublishDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobPublishDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobPublishDateTextFieldActionPerformed

    private void jobFinalApplyDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobFinalApplyDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobFinalApplyDateTextFieldActionPerformed

    private void postJobjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postJobjButtonActionPerformed
        resumesViewPanel.setVisible(false);
        addJobPanel.setVisible(false);
        jobListPanel.setVisible(false);
        addJobEducationPanel.setVisible(true);
        
    }//GEN-LAST:event_postJobjButtonActionPerformed

    private void bachelorDegreejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bachelorDegreejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bachelorDegreejComboBoxActionPerformed

    private void associateDegreejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associateDegreejComboBoxActionPerformed
        EducationListModel associationListModel = EducationListModel.getInstance();
        System.out.print(associateDegreejComboBox.getSelectedItem());
        associationListModel.add((String)associateDegreejComboBox.getSelectedItem());
        
        System.out.print(associateDegreejList.getModel());
        
        associateDegreejList.validate();
    }//GEN-LAST:event_associateDegreejComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel addJobEducationPanel;
    private javax.swing.JPanel addJobPanel;
    private javax.swing.JComboBox associateDegreejComboBox;
    private javax.swing.JList associateDegreejList;
    private javax.swing.JComboBox bachelorDegreejComboBox;
    private javax.swing.JList bachelorDegreejList;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JComboBox doctoralDegreejComboBox;
    private javax.swing.JList doctoralDegreejList;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JMenuItem generateJobMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JCheckBox jobDayJCheckBox;
    private javax.swing.JTextField jobExperienceTextField;
    private javax.swing.JTextField jobFinalApplyDateTextField;
    private javax.swing.JPanel jobListPanel;
    private javax.swing.JCheckBox jobNightJCheckBox;
    private javax.swing.JTextField jobPositionsTextField;
    private javax.swing.JTextField jobPublishDateTextField;
    private javax.swing.JTextField jobSalaryTextField;
    private javax.swing.JTextField jobTitleTextField;
    private javax.swing.JComboBox masterDegreejComboBox;
    private javax.swing.JList masterDegreejList;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JButton postJobjButton;
    private javax.swing.JList resumeJListMainScreen;
    private javax.swing.JPanel resumesViewListPanel;
    private javax.swing.JPanel resumesViewPanel;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

}

